FROM node:20-alpine3.17 

WORKDIR /opt/src

COPY public public
COPY src src 
COPY .eslintrc.json .
COPY next-env.d.ts .
COPY next.config.js .
COPY package.json .
COPY postcss.config.js .
COPY tailwind.config.ts .
COPY tsconfig.json .

ENTRYPOINT [ "sh", "-c", "npm i && npm run build" ]